spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    url: ${SPRING_FLYWAY_URL:${SPRING_DATASOURCE_URL}}
    user: ${SPRING_FLYWAY_USER:${SPRING_DATASOURCE_USERNAME}}
    password: ${SPRING_FLYWAY_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}
    locations:
      - classpath:db/migration
      - classpath:db/devdata
  cloud:
    aws:
      sqs:
        endpoint: ${SPRING_CLOUD_AWS_SQS_ENDPOINT}
